---
title: "Experience"
---

## Field Experience

### Low-Tech Process-Based Restoration (LTPBR) Field Work
**Colorado State University – Lower Elkhorn Creek | Spring 2026**

- Measured surface and groundwater levels to assess hydrological impacts of LTPBR structure installation
- Collected streamflow discharge data before and after LTPBR installation using a flowtracker
- Measured stream depth at 10-meter intervals along the reach between upstream and downstream sensors to quantify sediment depth and deposition

### Natural Resource Ecology & Measurement
**Colorado State University – Mountain Campus | Summer 
2024**

- Identified 120 different plant and animal species of 
Northern Colorado Region
- Assessed mountain  shrub, ponderosa pine/aspen, lodgepole pine, 
spruce-fir, and alpine ecosystems
- Collected recreation, watershed, range, wildlife, and forestry data using 
quadrants, line-intercepts, transects, and point-centered quarters
- Generated written reports for each ecosystem assessed

### Limnology Field Work
**Colorado State University - Horsetooth Reservoir | Fall 2024**

- Collected depth profiles: temperature, DO content, pH, water chemistry, 
and algae/zooplankton sampling
- Utilized Van Dorn bottles, Sonde, and macroinvertebrate nets for sampling

### Snow Hydrology Field Work
**Colorado State University - Cameron Pass | Fall 2024**

- Collected snowpack data at Cameron Pass via core samples
- Analyzed Joe Wright SNOTEL station data
